### PR TITLE
Create harbour-scoreboard-sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Swedish translation if wanted. Don't know why, but help text doesn't translate. Only topic translated on help page in my tests.

### CODE REVIEW

**Comment by Jollailija** [comment]
Tack! I am really busy with my studies atm, but I'll look into this at weekend. I think that translations don't support multi-line text, but I think a workaround exists (I've seen someone using multiple qsTr strings, one for each new line).

**Comment by Jollailija** [comment]
Hey eson57, could you also translate the store information? Thanks!

**Comment by eson57** [comment]
Of course! What file are you referring to?

**Comment by Jollailija** [comment]
The store page :P

**Comment by Jollailija** [comment]
I can provide you with it as a file, hang on a sec

**Comment by Jollailija** [comment]
Here, go wild: https://github.com/Jollailija/scoreboard/blob/master/storepage.txt

**Comment by eson57** [comment]
Coming up asap.  :)

**Comment by Jollailija** [comment]
No hurry, I am busy with the multi line translation thingy

**Pull request merged**
