### PR TITLE
Create storepage-sv.txt

### PR DESCRIPTION
**Pull request by eson57**
Translation done.  ;)

### CODE REVIEW

**Comment by Jollailija** [comment]
I fixed your swedish translation (multi line thingy broke it), try it out! I need to take new screenshots because SFOS 2.0 look different, so if you want to correct something, you got some time before I submit the app for QA.

**Comment by Jollailija** [comment]
Oops, sorry for extra trouble, the store only supports Finnish, English and Chinese for the storepage description. :( Well, thanks anyway, maybe I will need it some day. But the app localization is still much needed, many thanks for it!

**Comment by eson57** [comment]
Actually, help page still don't translate on my device. Scoreboard is fresh install.

**Comment by Jollailija** [comment]
Try a reboot. I just submitted the app, so this is really uncomfortable...

**Comment by Jollailija** [comment]
It should have a translated name also in the app drawer. Is "sv" the right language tag?

**Comment by eson57** [comment]
Yes, sv is correct. Reboot didn't help.

**Comment by Jollailija** [comment]
Did the reboot help? Does it say version 0.1.1-1 on the about page?

**Comment by eson57** [comment]
version number says 0.1.0-1

**Comment by Jollailija** [comment]
Then you have the wrong version. Try building it again from sources.

**Comment by Jollailija** [comment]
Wait, I can actually provide the RPM
Here: https://github.com/Jollailija/scoreboard/releases/tag/0.1.1-1

**Comment by eson57** [comment]
Yep, that's better!  :)

**Comment by Jollailija** [comment]
Cool! The new version is now also available at OpenRepos and soon it will be available in the store! Thanks for your work! If you want, you could also translate https://github.com/Jollailija/simplestopwatch it literally has 4 strings to translate

**Comment by eson57** [comment]
I'll take a look at it.

**Pull request merged**
