### PR TITLE
Update harbour-scoreboard-sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Translated new/moved strings

### CODE REVIEW

**Comment by Jollailija** [comment]
Thanks for updating the translation! Next time please wait for me to ping you about it because this is not the final UI version for the next release and many things are going to change & break the translation over and over again. I don't want to stress you out with this :)

**Comment by eson57** [comment]
Ok, I'll be waiting then.  :+1:

**Comment by Jollailija** [comment]
Okay, UI bits containing text should be ready now. No hurry, I need to fin(n)ish the Finnish translation myself.

**Comment by Jollailija** [comment]
Oops, fixed a couple of lines, everything is ready now.

**Comment by eson57** [comment]
Okay, that was almost a total remake. ;)

**Pull request merged**
