### PR TITLE
get rid of yaml, fix qml deploy path, make it deploy

### PR DESCRIPTION
**Pull request by kimmoli**
The %{_bindir} -line in .spec caused the problem. made some minor cleanups also.

### CODE REVIEW

**Comment by kimmoli** [comment]
Disclaimer; Not tested, just built.

**Comment by Jollailija** [comment]
Thank you so much! I'll mention you at the about page :)

**Comment by Jollailija** [comment]
There is a minor "bug", I don't see the qml files in the editor :)

**Comment by Jollailija** [comment]
Also, it does build but it doesn't run. But other than that, great job! :+1:  /sarcasm

**Comment by kimmoli** [comment]
To see QML in SDK, you need to add them in OTHER_FILES
e.g.

```
qml/* \
qml/pages/* \
```

**Comment by Jollailija** [comment]
Okay. Does it also make the app work? I can't run it.
Edit: It doesn't seem to make the app work. At least not on the emulator. Next I will test it on device.
Edit 2: It works on the device. Yay! Also, super fast startup time since only qml :) Doesn't work on the emulator at all anymore. Too bad.

**Pull request merged**
