### PR TITLE
fix qml files install

### PR DESCRIPTION
**Pull request by kimmoli**

### CODE REVIEW

**Comment by kimmoli** [comment]
It did not correctly install files in qml/pages -folder

**Comment by kimmoli** [comment]
Tip: if the app fails to start from launcher (clicking icon) - cover just shows spinner for few seconds and then disappears.
Errors can be seen running this on console while starting it:

```
devel-su journalctl -f
```

If there is nothing, use e.g. following to check is it stuck in bg. if it is, kill the process and try again.

```
ps ax | grep harbour-scoreboard
```

**Comment by Jollailija** [comment]
Thanks! Does it work on the emulator? Edit: it doesn't :( Is there any way I can make it work on the emulator? I don't have a Jolla Tablet so I can't try out the UI. Should I create another project and then just pull the qml files from that one to this one?

**Comment by kimmoli** [comment]
? dunno, i don't use emulator, just devices.

**Comment by Jollailija** [comment]
Okay. I'll make another app and write some scripts to sync the qml files. Thank you and good night!

**Pull request merged**
